/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from torre.Models.Coordinate **/
    export interface Coordinate {
        Longitude: number;
        Latitude: number;
    }
    /** Generated from torre.Models.Markers.MarkerEditModel **/
    export interface MarkerEditModel {
        Id: string;
        Name: string;
        Content: string;
        Icon: string;
        Longitude: number;
        Latitude: number;
    }
    /** Generated from torre.Models.Markers.MarkerModel **/
    export interface MarkerModel {
        Id: string;
        Name: string;
        Content: string;
        Icon: string;
        Longitude: number;
        Latitude: number;
    }
}
