/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from torre.Models.Coordinate **/
    export interface Coordinate {
        Longitude: number;
        Latitude: number;
    }
    /** Generated from torre.Models.MarkerViewModel **/
    export interface MarkerViewModel {
        Id: string;
        Name: string;
        Longitude: number;
        Latitude: number;
    }
}
